name: PCK.AUTOMIC_ORACLE
source: ae
binaries: 
- timestamp: disabled
  object: RESOURCES/PCK.AUTOMIC_ORACLE.PRV.CUSTOM_TYPES
  resources: 
  - name: COMPONENT#DATABASE_ORACLE
    type: TEXT
    path: ara/types/component/Database Oracle.xml
    version: 5.0
  - name: DEPLOYMENTTARGET#DATABASE_ORACLE
    type: TEXT
    path: ara/types/deploymenttarget/Database Oracle.xml
    version: 5.0
- object: RESOURCES/LIBS/PCK.AUTOMIC_ORACLE.PRV.STORE
  resources: 
  - name: ORACLETOOL.JAR
    type: BINARY
    path: tools/oracle-tool/target/oracle-tool.jar
    version: 1.0.0
