name: PCK.AUTOMIC_ORACLE_DB
source: ae
binaries: 
- object: RESOURCES/PCK.AUTOMIC_ORACLE_DB.PRV.CUSTOM_TYPES
  timestamp: disabled
  resources: 
  - name: COMPONENT#DATABASE_ORACLE#2
    type: TEXT
    path: ara/types/component/Database Oracle.xml
    version: 1.0.0
  - name: DEPLOYMENTTARGET#DATABASE_ORACLE#1
    type: TEXT
    path: ara/types/deploymenttarget/Database Oracle.xml
    version: 1.0.0
- object: RESOURCES/LIBS/PCK.AUTOMIC_ORACLE_DB.PRV.STORE
  resources: 
  - name: ORACLEDBTOOL.JAR
    type: BINARY
    path: tools/oracle-db-tool/target/oracle-db-tool.jar
    version: 1.0.3
